[manifest]
summary = "Aiken on-chain project implementing the GiftCard mint + redeem validators"

[[files]]
source = "aiken.toml.jinja"
dest = "aiken.toml"

[[files]]
source = "Justfile.jinja"
dest = "Justfile"

[[files]]
source = "lib/helpers.ak"
dest = "lib/helpers.ak"

[[files]]
source = "validators/giftcard.ak"
dest = "validators/giftcard.ak"
